apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: vivek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgressql
        image: postgres:17.10
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "P@ssw0rd@123"
        - name: POSTGRES_DB
          value: "axiondb"
